# Generated by Django 4.1.1 on 2022-09-19 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_uploadimage_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='unfollower',
            field=models.ManyToManyField(related_name='unfollower', to=settings.AUTH_USER_MODEL),
        ),
    ]
